name = "tonghoptintuc"
main = "src/index.ts"
compatibility_date = "2026-04-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[observability]
enabled = true
logs = { enabled = true, persist = true, invocation_logs = true }
traces = { enabled = true, persist = true }

[[kv_namespaces]]
binding = "RUN_LOGS"
id = "617276efc36a4de09a11172513dd9435"

[vars]
NODE_ENV = "production"
LOG_LEVEL = "info"
FACEBOOK_PAGE_ID = "976630878877881"
FB_TOKEN = "EAAXlhPlUreUBRET2NQFkOE09OwMXnRHrubsSoeou93KjOT80ZBG8QQi6fBLWEeji3e38mEicrQXEm8RnqFumAbaXJbN1CPkLJx0qSghvZCdYZBwPVyPmXB0Bf7rREBhuSyHk27dpcs6ZAeH2xV3POu86sMt8wwZCJ1JZAkwsdusHzbeOUaoDjdbq5n2qrLhfZBQqwVL66zLZBbHtafHim2YL"
TELEGRAM_BOT_TOKEN = "8750690448:AAEFZdUY2fjK3BRoWoYTDpnf7gUavIUAwvE"
TELEGRAM_CHAT_ID = "8125484259"

[env.production]
name = "tonghoptintuc-production"
vars = { NODE_ENV = "production", LOG_LEVEL = "info", FACEBOOK_PAGE_ID = "976630878877881" }

# Cron disabled - dùng GitHub Actions thay thế
# [triggers]
# crons = ["0 * * * *", "30 * * * *"]